# Chen Eliyahou Meital Birka

# 312490675 , 311124283

compile: bin
	javac -cp src -d bin src/Factorial.java src/DescribeNumbers.java src/Sort.java


        
run1:	
	java -cp bin Factorial 5


        
run2:
	java -cp bin DescribeNumbers 12 2 3 -9 8



run3:

	java -cp bin Sort desc 12 2 3 -9 8

        
bin:
	mkdir bin
